name: rst_superapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  local_auth: ^2.2.0
  qr_flutter: ^4.0.0
  http: 1.2.2
  dio: ^5.0.0
  permission_handler: 11.3.1
  open_file: 3.3.2
  path_provider: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0

flutter:


  uses-material-design: true
  assets:
  - assets/logo.png

